/** Tests for the copyright year formatter utility. */

import { assert } from "jsr/assert";
import { FakeTime } from "jsr:@std/testing/time@1";
import { describe, it } from "jsr/testing-bdd";
import { faker, seedTestFaker, TEST_FAKER_REF_DATE } from "../../test/faker.ts";
import { formatCopyrightYears } from "./copyright.ts";

// Seed range: 801–899 (see AGENTS.md "TypeScript Tests And Faker")
const TEST_SEED = 801;
const TEST_CURRENT_YEAR = TEST_FAKER_REF_DATE.getUTCFullYear();
const STRICTLY_PAST_REF_DATE = new Date("2026-01-01T00:00:00.000Z");
const STRICTLY_FUTURE_REF_DATE = new Date("2026-12-31T23:59:59.999Z");

function captureConsoleWarning(run: () => void): string {
  const originalWarn = globalThis.console.warn;
  let warningMessage = "";

  globalThis.console.warn = (...args: unknown[]) => {
    warningMessage = args.map(String).join(" ");
  };

  try {
    run();
    return warningMessage;
  } finally {
    globalThis.console.warn = originalWarn;
  }
}

describe("formatCopyrightYears", () => {
  it("returns single year when start year equals current year", () => {
    seedTestFaker(TEST_SEED);
    const result = formatCopyrightYears(TEST_CURRENT_YEAR, TEST_CURRENT_YEAR);
    assert(result === String(TEST_CURRENT_YEAR));
  });

  it("returns year range when start year is less than current year", () => {
    seedTestFaker(TEST_SEED + 1);
    const pastYear = TEST_CURRENT_YEAR - faker.number.int({ min: 1, max: 10 });
    const result = formatCopyrightYears(pastYear, TEST_CURRENT_YEAR);
    assert(result === `${pastYear}-${TEST_CURRENT_YEAR}`);
  });

  it("logs warning and returns start year when start year is in the future", () => {
    seedTestFaker(TEST_SEED + 2);
    const futureYear = TEST_CURRENT_YEAR +
      faker.number.int({ min: 1, max: 10 });

    const warningMessage = captureConsoleWarning(() => {
      const result = formatCopyrightYears(futureYear, TEST_CURRENT_YEAR);
      assert(result === String(futureYear));
    });

    assert(
      warningMessage.includes(
        `blogStartYear (${futureYear}) is set to a future year`,
      ),
    );
  });

  it("logs warning and returns current year when start year is invalid string", () => {
    seedTestFaker(TEST_SEED + 3);
    const invalidYear = "not-a-year";

    const warningMessage = captureConsoleWarning(() => {
      const result = formatCopyrightYears(invalidYear, TEST_CURRENT_YEAR);
      assert(result === String(TEST_CURRENT_YEAR));
    });

    assert(
      warningMessage.includes(
        `blogStartYear value "${invalidYear}" is not in a valid YYYY format`,
      ),
    );
  });

  it("logs warning and returns current year when start year is NaN", () => {
    seedTestFaker(TEST_SEED + 4);

    const warningMessage = captureConsoleWarning(() => {
      const result = formatCopyrightYears(NaN, TEST_CURRENT_YEAR);
      assert(result === String(TEST_CURRENT_YEAR));
    });

    assert(
      warningMessage.includes(
        `blogStartYear value "NaN" is not in a valid YYYY format`,
      ),
    );
  });

  it("handles numeric string start year correctly", () => {
    seedTestFaker(TEST_SEED + 5);
    const pastYear = TEST_CURRENT_YEAR - faker.number.int({ min: 1, max: 10 });
    const result = formatCopyrightYears(String(pastYear), TEST_CURRENT_YEAR);
    assert(result === `${pastYear}-${TEST_CURRENT_YEAR}`);
  });

  it("uses current year from Date.now() when not provided", () => {
    seedTestFaker(TEST_SEED + 6);
    const time = new FakeTime(TEST_FAKER_REF_DATE);

    try {
      const result = formatCopyrightYears(TEST_CURRENT_YEAR);
      assert(result === String(TEST_CURRENT_YEAR));
    } finally {
      time.restore();
    }
  });

  it("handles years generated by faker in the past", () => {
    seedTestFaker(TEST_SEED + 7);
    const pastDate = faker.date.past({
      years: 10,
      refDate: STRICTLY_PAST_REF_DATE,
    });
    const pastYear = pastDate.getUTCFullYear();
    const result = formatCopyrightYears(pastYear, TEST_CURRENT_YEAR);
    assert(result === `${pastYear}-${TEST_CURRENT_YEAR}`);
  });

  it("handles years generated by faker in the future", () => {
    seedTestFaker(TEST_SEED + 8);
    const futureDate = faker.date.future({
      years: 5,
      refDate: STRICTLY_FUTURE_REF_DATE,
    });
    const futureYear = futureDate.getUTCFullYear();

    const warningMessage = captureConsoleWarning(() => {
      const result = formatCopyrightYears(futureYear, TEST_CURRENT_YEAR);
      assert(result === String(futureYear));
    });

    assert(
      warningMessage.includes(
        `blogStartYear (${futureYear}) is set to a future year`,
      ),
    );
  });
});
