/** Tests for the copyright year formatter utility. */

import { assert } from "jsr/assert";
import { describe, it } from "jsr/testing-bdd";
import { faker } from "npm/faker-js";
import { formatCopyrightYears } from "./copyright.ts";

// Seed range: 801–899 (see AGENTS.md §5.10)
const TEST_SEED = 801;

describe("formatCopyrightYears", () => {
  it("returns single year when start year equals current year", () => {
    faker.seed(TEST_SEED);
    const currentYear = new Date().getFullYear();
    const result = formatCopyrightYears(currentYear, currentYear);
    assert(result === String(currentYear));
  });

  it("returns year range when start year is less than current year", () => {
    faker.seed(TEST_SEED + 1);
    const currentYear = new Date().getFullYear();
    const pastYear = currentYear - faker.number.int({ min: 1, max: 10 });
    const result = formatCopyrightYears(pastYear, currentYear);
    assert(result === `${pastYear}-${currentYear}`);
  });

  it("logs warning and returns start year when start year is in the future", () => {
    faker.seed(TEST_SEED + 2);
    const currentYear = new Date().getFullYear();
    const futureYear = currentYear + faker.number.int({ min: 1, max: 10 });

    const consoleWarnSpy = globalThis.console.warn;
    let warningMessage = "";
    globalThis.console.warn = (message: string) => {
      warningMessage = message;
    };

    try {
      const result = formatCopyrightYears(futureYear, currentYear);
      assert(result === String(futureYear));
      assert(
        warningMessage.includes(
          `blogStartYear (${futureYear}) is set to a future year`,
        ),
      );
    } finally {
      globalThis.console.warn = consoleWarnSpy;
    }
  });

  it("logs warning and returns current year when start year is invalid string", () => {
    faker.seed(TEST_SEED + 3);
    const currentYear = new Date().getFullYear();
    const invalidYear = "not-a-year";

    const consoleWarnSpy = globalThis.console.warn;
    let warningMessage = "";
    globalThis.console.warn = (message: string) => {
      warningMessage = message;
    };

    try {
      const result = formatCopyrightYears(invalidYear, currentYear);
      assert(result === String(currentYear));
      assert(
        warningMessage.includes(
          `blogStartYear value "${invalidYear}" is not in a valid YYYY format`,
        ),
      );
    } finally {
      globalThis.console.warn = consoleWarnSpy;
    }
  });

  it("logs warning and returns current year when start year is NaN", () => {
    faker.seed(TEST_SEED + 4);
    const currentYear = new Date().getFullYear();

    const consoleWarnSpy = globalThis.console.warn;
    let warningMessage = "";
    globalThis.console.warn = (message: string) => {
      warningMessage = message;
    };

    try {
      const result = formatCopyrightYears(NaN, currentYear);
      assert(result === String(currentYear));
      assert(
        warningMessage.includes(
          `blogStartYear value "NaN" is not in a valid YYYY format`,
        ),
      );
    } finally {
      globalThis.console.warn = consoleWarnSpy;
    }
  });

  it("handles numeric string start year correctly", () => {
    faker.seed(TEST_SEED + 5);
    const currentYear = new Date().getFullYear();
    const pastYear = currentYear - 5;
    const result = formatCopyrightYears(String(pastYear), currentYear);
    assert(result === `${pastYear}-${currentYear}`);
  });

  it("uses current year from Date.now() when not provided", () => {
    faker.seed(TEST_SEED + 6);
    const currentYear = new Date().getFullYear();
    const result = formatCopyrightYears(currentYear);
    assert(result === String(currentYear));
  });

  it("handles years generated by faker in the past", () => {
    faker.seed(TEST_SEED + 7);
    faker.setDefaultRefDate(new Date());
    const currentYear = new Date().getFullYear();
    const pastDate = faker.date.past({ years: 10 });
    const pastYear = pastDate.getFullYear();
    const result = formatCopyrightYears(pastYear, currentYear);
    assert(result === `${pastYear}-${currentYear}`);
  });

  it("handles years generated by faker in the future", () => {
    faker.seed(TEST_SEED + 8);
    faker.setDefaultRefDate(new Date());
    const currentYear = new Date().getFullYear();
    // Ensure we generate a year strictly in the future by adding offset
    const futureDate = faker.date.future({ years: 5 });
    let futureYear = futureDate.getFullYear();

    // If the generated year equals current year, force it to be in the future
    if (futureYear <= currentYear) {
      futureYear = currentYear + 1;
    }

    const consoleWarnSpy = globalThis.console.warn;
    let warningMessage = "";
    globalThis.console.warn = (message: string) => {
      warningMessage = message;
    };

    try {
      const result = formatCopyrightYears(futureYear, currentYear);
      assert(result === String(futureYear));
      assert(
        warningMessage.includes(
          `blogStartYear (${futureYear}) is set to a future year`,
        ),
      );
    } finally {
      globalThis.console.warn = consoleWarnSpy;
    }
  });
});
