export const PAGEHEAD_CONTEXT_BREAKPOINT = "52rem";
export const HEADER_NAV_BREAKPOINT = "64rem";
export const FEATURE_RAIL_BREAKPOINT = "66rem";
export const POST_RAIL_BREAKPOINT = FEATURE_RAIL_BREAKPOINT;
export const POST_MOBILE_TOOLS_MEDIA_QUERY =
  `(width < ${POST_RAIL_BREAKPOINT})`;
