/**
 * md-to-tsx — Converts LumeCMS-generated Markdown posts to `.page.tsx` format.
 *
 * Why not use existing converters?
 * - `markdown-to-ts` converts Markdown *tables* to TypeScript interfaces.
 * - MDX / `remark-react` generate React JSX components.
 * Neither produces the plain HTML-string template (`string => \`...\``) that
 * Lume pages require. This script does exactly that.
 *
 * Reads a Markdown file with YAML frontmatter, converts the body to HTML, and
 * writes a `.page.tsx` file alongside the source. Runs `deno fmt` on the
 * result automatically.
 *
 * Exit codes:
 *   0 — all files converted successfully
 *   1 — one or more errors
 *
 * @example
 * ```ts ignore
 * // Convert a single post:
 * // deno task md-to-tsx src/posts/my-post.md
 *
 * // Convert all .md files in src/posts/:
 * // deno task md-to-tsx
 * ```
 */

// ── Types ─────────────────────────────────────────────────────────────────────

/** Structured frontmatter extracted from a Markdown post. */
export type Frontmatter = {
  readonly title: string;
  readonly date: string;
  readonly description: string | undefined;
  readonly tags: ReadonlyArray<string> | undefined;
};

// ── Frontmatter parser ────────────────────────────────────────────────────────

/** Strips surrounding single or double quotes from a YAML scalar value. */
function unquote(raw: string): string {
  const v = raw.trim();
  if (
    (v.startsWith('"') && v.endsWith('"')) ||
    (v.startsWith("'") && v.endsWith("'"))
  ) {
    return v.slice(1, -1);
  }
  return v;
}

/**
 * Parses a Markdown document with `---`-delimited YAML frontmatter.
 *
 * Handles the fields generated by LumeCMS: `title`, `date`, `description`,
 * and `tags` (both block-sequence and inline-array forms). Returns the
 * structured frontmatter and the trimmed body text.
 *
 * @example
 * ```ts
 * import { assertEquals } from "jsr:@std/assert/equals";
 *
 * const { frontmatter, body } = parseDocument(
 *   "---\ntitle: Hello\ndate: 2026-01-01\n---\n\nWorld.",
 * );
 * assertEquals(frontmatter.title, "Hello");
 * assertEquals(frontmatter.date, "2026-01-01");
 * assertEquals(body, "World.");
 * ```
 */
export function parseDocument(
  source: string,
): { frontmatter: Frontmatter; body: string } {
  const lines = source.split("\n");

  if (lines[0]?.trim() !== "---") {
    return {
      frontmatter: {
        title: "Untitled",
        date: new Date().toISOString().slice(0, 10),
        description: undefined,
        tags: undefined,
      },
      body: source.trim(),
    };
  }

  let closeIndex = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i]?.trim() === "---") {
      closeIndex = i;
      break;
    }
  }

  if (closeIndex === -1) {
    throw new Error("Malformed frontmatter: missing closing `---`.");
  }

  const fmLines = lines.slice(1, closeIndex);
  const body = lines.slice(closeIndex + 1).join("\n").trim();

  const raw: Record<string, string | string[]> = {};
  let currentKey: string | undefined;

  for (const line of fmLines) {
    // YAML block-sequence item (indented `- value`)
    const listItem = line.match(/^[ \t]+-\s+(.+)$/);
    if (listItem && currentKey !== undefined) {
      const existing = raw[currentKey];
      if (Array.isArray(existing)) {
        existing.push(unquote(listItem[1] ?? ""));
      } else {
        raw[currentKey] = [unquote(listItem[1] ?? "")];
      }
      continue;
    }

    // `key: value` pair
    const kv = line.match(/^([\w]+)\s*:\s*(.*)/);
    if (!kv) continue;

    currentKey = kv[1];
    if (currentKey === undefined) continue;
    const rawValue = (kv[2] ?? "").trim();

    if (rawValue === "" || rawValue === "[]") {
      // Block sequence will follow (or explicit empty array)
      raw[currentKey] = [];
    } else if (rawValue.startsWith("[")) {
      // Inline YAML array: [item1, item2]
      const inner = rawValue.slice(1, rawValue.lastIndexOf("]"));
      raw[currentKey] = inner
        .split(",")
        .map((s) => unquote(s.trim()))
        .filter(Boolean);
    } else {
      raw[currentKey] = unquote(rawValue);
    }
  }

  const rawDate = typeof raw["date"] === "string" ? raw["date"] : "";
  // Normalize ISO datetime strings and bare YAML dates to YYYY-MM-DD.
  const date = /^\d{4}-\d{2}-\d{2}/.test(rawDate)
    ? rawDate.slice(0, 10)
    : new Date().toISOString().slice(0, 10);

  return {
    frontmatter: {
      title: typeof raw["title"] === "string" ? raw["title"] : "Untitled",
      date,
      description: typeof raw["description"] === "string"
        ? raw["description"]
        : undefined,
      tags: Array.isArray(raw["tags"]) ? (raw["tags"] as string[]) : undefined,
    },
    body,
  };
}

// ── Markdown → HTML ───────────────────────────────────────────────────────────

/** Escapes `&`, `<`, `>` for safe embedding in HTML (used in code blocks). */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Processes inline Markdown elements within a text run.
 *
 * Handles code spans, bold (`**`/`__`), italic (`*`/`_`), links, and images.
 * Code spans are extracted first so their content is not affected by other
 * rules.
 */
function processInline(text: string): string {
  // Extract code spans and replace with private-use-area placeholders
  // (\ue000) to prevent other rules from processing their content.
  const spans: string[] = [];
  const escaped = text.replace(/`([^`]+)`/g, (_, code: string) => {
    const idx = spans.length;
    spans.push(`<code>${escapeHtml(code)}</code>`);
    return `\ue000${idx}\ue000`;
  });

  let result = escaped
    // Images must come before links (same syntax with leading `!`).
    .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/__([^_]+)__/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/_([^_]+)_/g, "<em>$1</em>");

  // Restore code spans.
  result = result.replace(
    /\ue000(\d+)\ue000/g,
    (_, idx: string) => spans[Number(idx)] ?? "",
  );

  return result;
}

type BlockState = "normal" | "paragraph" | "ul" | "ol" | "blockquote" | "code";

/**
 * Converts a Markdown string to an HTML string.
 *
 * Handles the elements generated by LumeCMS's Markdown editor: fenced code
 * blocks, headings (h1–h6), paragraphs, unordered and ordered lists,
 * blockquotes, horizontal rules, and inline elements (bold, italic, code
 * spans, links, images).
 *
 * @example
 * ```ts
 * import { assertEquals } from "jsr:@std/assert/equals";
 *
 * const html = markdownToHtml("## Hello\n\nWorld.");
 * assertEquals(html, "<h2>Hello</h2>\n\n<p>World.</p>");
 * ```
 */
export function markdownToHtml(md: string): string {
  const lines = md.split("\n");
  const blocks: string[] = [];
  let state: BlockState = "normal";
  let buffer: string[] = [];
  let codeLang = "";

  function flushParagraph(): void {
    if (buffer.length === 0) return;
    blocks.push(`<p>${processInline(buffer.join(" "))}</p>`);
    buffer = [];
  }

  function flushList(tag: "ul" | "ol"): void {
    if (buffer.length === 0) return;
    const items = buffer
      .map((item) => `  <li>${processInline(item)}</li>`)
      .join("\n");
    blocks.push(`<${tag}>\n${items}\n</${tag}>`);
    buffer = [];
  }

  function flushBlockquote(): void {
    if (buffer.length === 0) return;
    blocks.push(
      `<blockquote>\n  <p>${
        processInline(buffer.join(" "))
      }</p>\n</blockquote>`,
    );
    buffer = [];
  }

  function flushCurrent(): void {
    if (state === "paragraph") flushParagraph();
    else if (state === "ul") flushList("ul");
    else if (state === "ol") flushList("ol");
    else if (state === "blockquote") flushBlockquote();
  }

  for (const line of lines) {
    // ── Inside a fenced code block ──────────────────────────────────────────
    if (state === "code") {
      if (/^```\s*$/.test(line)) {
        const langAttr = codeLang ? ` class="language-${codeLang}"` : "";
        blocks.push(
          `<pre><code${langAttr}>${
            escapeHtml(buffer.join("\n"))
          }\n</code></pre>`,
        );
        buffer = [];
        codeLang = "";
        state = "normal";
      } else {
        buffer.push(line);
      }
      continue;
    }

    // ── Opening code fence ──────────────────────────────────────────────────
    const fence = line.match(/^```(\w*)$/);
    if (fence) {
      flushCurrent();
      state = "code";
      codeLang = fence[1] ?? "";
      buffer = [];
      continue;
    }

    // ── Blank line ──────────────────────────────────────────────────────────
    if (line.trim() === "") {
      flushCurrent();
      state = "normal";
      continue;
    }

    // ── ATX heading ─────────────────────────────────────────────────────────
    const heading = line.match(/^(#{1,6})\s+(.+)$/);
    if (heading) {
      flushCurrent();
      const level = (heading[1] ?? "#").length;
      blocks.push(
        `<h${level}>${processInline((heading[2] ?? "").trim())}</h${level}>`,
      );
      state = "normal";
      continue;
    }

    // ── Horizontal rule ──────────────────────────────────────────────────────
    if (/^(-{3,}|\*{3,}|_{3,})$/.test(line.trim())) {
      flushCurrent();
      blocks.push("<hr>");
      state = "normal";
      continue;
    }

    // ── Unordered list item ─────────────────────────────────────────────────
    const ulItem = line.match(/^[-*+]\s+(.+)$/);
    if (ulItem) {
      if (state !== "ul") {
        flushCurrent();
        state = "ul";
        buffer = [];
      }
      buffer.push(ulItem[1] ?? "");
      continue;
    }

    // ── Ordered list item ────────────────────────────────────────────────────
    const olItem = line.match(/^\d+\.\s+(.+)$/);
    if (olItem) {
      if (state !== "ol") {
        flushCurrent();
        state = "ol";
        buffer = [];
      }
      buffer.push(olItem[1] ?? "");
      continue;
    }

    // ── Blockquote ───────────────────────────────────────────────────────────
    const bq = line.match(/^>\s?(.*)$/);
    if (bq) {
      if (state !== "blockquote") {
        flushCurrent();
        state = "blockquote";
        buffer = [];
      }
      buffer.push(bq[1] ?? "");
      continue;
    }

    // ── Regular paragraph text ───────────────────────────────────────────────
    if (state !== "paragraph") {
      flushCurrent();
      state = "paragraph";
      buffer = [];
    }
    buffer.push(line);
  }

  // Flush any content remaining at end of input.
  flushCurrent();

  return blocks.join("\n\n");
}

// ── TSX generator ─────────────────────────────────────────────────────────────

/**
 * Escapes content for safe embedding inside a TypeScript template literal.
 *
 * Replaces `\`, `` ` ``, and `${` so they are treated as literal characters
 * rather than escape sequences or template expressions.
 *
 * @example
 * ```ts
 * import { assertEquals } from "jsr:@std/assert/equals";
 *
 * assertEquals(escapeTsTemplateLiteral("a`b${c}"), "a\\`b\\${c}");
 * ```
 */
export function escapeTsTemplateLiteral(text: string): string {
  return text
    .replace(/\\/g, "\\\\") // Must be first — avoids double-escaping.
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

/** Strips the leading H1 heading from body text if it matches the post title. */
function stripLeadingH1(body: string, title: string): string {
  const firstLine = body.split("\n")[0]?.trim() ?? "";
  const h1 = firstLine.match(/^#\s+(.+)$/);
  if (h1 && (h1[1]?.trim() ?? "").toLowerCase() === title.toLowerCase()) {
    return body.slice(firstLine.length).replace(/^\n+/, "");
  }
  return body;
}

/** Formats a string export, wrapping to the next line when it would exceed 80 chars. */
function formatStringExport(name: string, value: string): string {
  const inline = `export const ${name} = "${value}";`;
  return inline.length <= 80 ? inline : `export const ${name} =\n  "${value}";`;
}

/**
 * Generates the full `.page.tsx` source from parsed frontmatter and HTML body.
 *
 * @example
 * ```ts
 * import { assertStringIncludes } from "jsr:@std/assert/string-includes";
 *
 * const src = generateTsx(
 *   { title: "Hello", date: "2026-01-01", description: undefined, tags: undefined },
 *   "<p>World.</p>",
 *   "hello.md",
 * );
 * assertStringIncludes(src, 'export const title = "Hello"');
 * assertStringIncludes(src, 'export const date = new Date("2026-01-01")');
 * assertStringIncludes(src, "<p>World.</p>");
 * ```
 */
export function generateTsx(
  frontmatter: Frontmatter,
  html: string,
  sourceFilename: string,
): string {
  const { title, date, description, tags } = frontmatter;
  const safeTitle = title.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const lines: string[] = [];

  lines.push(
    `/** ${safeTitle} — converted from ${sourceFilename}. */`,
    "",
    `export const title = "${safeTitle}";`,
    `/** Publication date. */`,
    `export const date = new Date("${date}");`,
  );

  if (description !== undefined) {
    const safeDesc = description.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    lines.push(
      `/** Post meta description. */`,
      formatStringExport("description", safeDesc),
    );
  }

  if (tags !== undefined && tags.length > 0) {
    const tagList = tags.map((t) => `"${t.replace(/"/g, '\\"')}"`).join(", ");
    lines.push(`/** Post tags. */`, `export const tags = [${tagList}];`);
  }

  lines.push(
    "",
    `/** Renders the post body. */`,
    `export default (_data: Lume.Data, _helpers: Lume.Helpers): string =>`,
    `  \`${escapeTsTemplateLiteral(html)}\`;`,
  );

  return lines.join("\n") + "\n";
}

// ── Entry point ───────────────────────────────────────────────────────────────

/** Converts one `.md` file to `.page.tsx` and auto-formats the result. */
async function convertFile(inputPath: string): Promise<void> {
  const source = await Deno.readTextFile(inputPath);
  const { frontmatter, body } = parseDocument(source);
  const cleanBody = stripLeadingH1(body, frontmatter.title);
  const html = markdownToHtml(cleanBody);

  const outputPath = inputPath.replace(/\.md$/, ".page.tsx");
  const sourceFilename = inputPath.split("/").pop() ?? inputPath;
  await Deno.writeTextFile(
    outputPath,
    generateTsx(frontmatter, html, sourceFilename),
  );

  // Auto-format so the output passes `deno fmt` immediately.
  const { success } = await new Deno.Command("deno", {
    args: ["fmt", outputPath],
    stdout: "null",
    stderr: "null",
  }).output();

  if (!success) console.warn(`  warn: deno fmt failed on ${outputPath}`);

  console.log(`  ${inputPath} → ${outputPath}`);
}

/** Discovers `.md` files and runs conversion. */
async function main(): Promise<void> {
  const paths = Deno.args.length > 0 ? [...Deno.args] : await (async () => {
    const found: string[] = [];
    for await (const entry of Deno.readDir("src/posts")) {
      if (entry.isFile && entry.name.endsWith(".md")) {
        found.push(`src/posts/${entry.name}`);
      }
    }
    return found;
  })();

  if (paths.length === 0) {
    console.log("No .md files found.");
    return;
  }

  let hasErrors = false;
  for (const path of paths) {
    try {
      await convertFile(path);
    } catch (err) {
      console.error(
        `  error: ${path}: ${err instanceof Error ? err.message : String(err)}`,
      );
      hasErrors = true;
    }
  }

  if (hasErrors) Deno.exit(1);
}

if (import.meta.main) await main();
