name: Git History

on:
    pull_request:

jobs:
    clean:
        name: Clean
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/developerc286/clean_git_history:v1.2.0
        steps:
            - name: Checkout code.
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0
            - name: Check clean Git history.
              run: clean_git_history "origin/${{ github.base_ref }}"
