# Build and deploy static content to Alibaba Cloud OSS
name: Deploy static content to OSS

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/site.yml"
      - ".tool-versions"
      - "_config.ts"
      - "_config/**"
      - "contracts/**"
      - "deno.json"
      - "deno.lock"
      - "package.json"
      - "package-lock.json"
      - "plugins/**"
      - "pnpm-lock.yaml"
      - "scripts/**"
      - "src/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "oss-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: development
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true

      - name: Lume build cache
        id: lume-cache      
        uses: actions/cache@v5
        with:
          path: _cache
          key: lume-cache-${{ runner.os }}-${{ hashFiles('_cache/**') }}

      - name: Run build task
        shell: bash
        run:
          deno task build

      - name: Deploy to Alibaba Cloud OSS
        uses: frenchvandal/aliyun-oss-cdn-sync-action@master
        with:
          role-oidc-arn: ${{ secrets.ALIBABA_CLOUD_ROLE_ARN }}
          oidc-provider-arn: ${{ secrets.ALIBABA_CLOUD_OIDC_PROVIDER_ARN }}
          role-session-name: ${{ github.run_id }}
          role-session-expiration: 3600
          input-dir: _site
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}
          audience: ${{ github.repository_id }}
          cdn-enabled: true
          cdn-base-url: ${{ secrets.OSS_CDN_BASE_URL }}
          cdn-actions: refresh
