# Build and deploy static content to Alibaba Cloud OSS
name: Deploy static content to OSS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "oss-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: development
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true

      - name: Deno install
        shell: bash
        run: |
          deno install \
            --allow-scripts=npm:@carbon/colors@11.48.0,npm:@carbon/feature-flags@1.1.0,npm:@carbon/grid@11.51.0,npm:@carbon/icons@11.76.0,npm:@carbon/layout@11.49.0,npm:@carbon/motion@11.42.0,npm:@carbon/styles@1.102.0,npm:@carbon/themes@11.69.0,npm:@carbon/type@11.55.0,npm:@ibm/plex-mono@1.1.0,npm:@ibm/plex-sans-arabic@1.1.0,npm:@ibm/plex-sans-devanagari@1.1.0,npm:@ibm/plex-sans-hebrew@1.1.0,npm:@ibm/plex-sans-thai-looped@1.1.0,npm:@ibm/plex-sans-thai@1.1.0,npm:@ibm/plex-sans@1.1.0,npm:@ibm/plex-serif@1.1.0,npm:@parcel/watcher@2.5.6,npm:esbuild@0.27.3,npm:lightningcss-cli@1.32.0


      - name: Run build task
        shell: bash
        run:
          deno task build

      - name: Deploy to Alibaba Cloud OSS
        uses: frenchvandal/aliyun-oss-cdn-sync-action@master
        with:
          role-oidc-arn: ${{ secrets.ALIBABA_CLOUD_ROLE_ARN }}
          oidc-provider-arn: ${{ secrets.ALIBABA_CLOUD_OIDC_PROVIDER_ARN }}
          role-session-name: ${{ github.run_id }}
          role-session-expiration: 3600
          input-dir: _site
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}
          audience: ${{ github.repository_id }}
          cdn-enabled: true
          cdn-base-url: ${{ secrets.OSS_CDN_BASE_URL }}
          cdn-actions: refresh
