# Build and deploy static content to Alibaba Cloud OSS
name: Deploy static content to OSS

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "oss-deploy"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: development
    runs-on: ubuntu-latest
    env:
      GITHUB_SERVER_URL: ${{ github.server_url }}
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      OSS_BUCKET: ${{ vars.OSS_BUCKET }}
      OSS_REGION: ${{ vars.OSS_REGION }}
      OSS_CDN_BASE_URL: ${{ vars.OSS_CDN_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true
      - name: Run build task
        shell: bash
        run: |
          DENO_TLS_CA_STORE=system deno task build
      - name: Configure Alibaba Cloud credentials
        id: aliyun-creds
        uses: frenchvandal/configure-aliyun-credentials-action@master
        with:
          audience: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY_OWNER }}
          role-to-assume: ${{ secrets.ALIBABA_CLOUD_ROLE_ARN }}
          oidc-provider-arn: ${{ secrets.ALIBABA_CLOUD_OIDC_PROVIDER_ARN }}
          role-session-name: github-action-session
          role-session-expiration: 1800
      - name: Deploy to Alibaba Cloud OSS
        uses: frenchvandal/deploy-oss@master
        with:
          input-dir: _site
          bucket: ${{ env.OSS_BUCKET }}
          region: ${{ env.OSS_REGION }}
          cdn-base-url: ${{ env.OSS_CDN_BASE_URL }}
          aliyun-access-key-id: ${{ steps.aliyun-creds.outputs.aliyun-access-key-id }}
          aliyun-access-key-secret: ${{ steps.aliyun-creds.outputs.aliyun-access-key-secret }}
          aliyun-security-token: ${{ steps.aliyun-creds.outputs.aliyun-security-token }}
